spring:
    application:
      name : backend-app
    profiles:
        active: @profiles.active@
    datasource:
        url: jdbc:postgresql://localhost:5432/bugtracker
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
      open-in-view: false

server:
    port: 8080
    servlet:
        context-path: /backend-app


